### ISSUE TITLE
how kubestacks can be used with terraform Cloud

### ISSUE THREAD

**Issue by DiemanXT1** [kbst/terraform-kubestack#116]
Hi,

I've been reading about kubestacks and I like the idea of gitops though we are using TF Cloud and bootstrap documentation focuses only on running TF locally or via pipeline. Is it possible to implement kuberstack on TF Cloud? Thank you

**Comment by pst** [comment]
Hey, thanks for reaching out. Terraform cloud is something I very much want to support. However, I don't think it is currently possible. There are three potential blockers to investigate (that I know of):

 1. Kubestack uses the [`terraform-provider-kustomize`](https://github.com/kbst/terraform-provider-kustomize) to integrate the cluster services into the Terraform plan/apply lifecycle. The provider is not available in the Terrafom registry yet. The recently announced [support for community providers](https://www.hashicorp.com/blog/announcing-the-terraform-0-13-beta/) should solve this, but unfortunately I haven't been lucky enough to get access to the beta. So I wasn't able to work on this yet.

 1. The [GKE module](https://github.com/kbst/terraform-kubestack/blob/c5f6efadf387a7208efdc42282067abf7fcb15c6/google/_modules/gke/cluster_role_binding.tf#L2) currently relies on a `external` data source that runs a `gcloud` CLI command to determine the current IAM account and ensure it has `cluster-admin` ClusterRole. This may or may not work in Terraform cloud (untested).

 1. Terraform cloud, last time I checked, did not allow tags to trigger a run. Kubestack's [GitOps flow](https://www.kubestack.com/framework/documentation/gitops-process#making-changes) relies on tags to promote a change from the ops environment to the critical apps environment.

I'll leave this issue open to track the requirements, so that support for Terraform cloud can be tested, as soon as the community provider feature is available.

**Comment by DiemanXT1** [comment]
Thank you for the prompt response

1. If I am honest kustomize is lesser of my concerns. I was able to compile it and TF Cloud picked it up from terraform.d/plugins/linux_amd64/ folder no problem. Where I am stuck is switching between ops and apps workspaces as TF Cloud always return default as workspace is something like terraform.workspace is used. How can I work around it?
2. We are on AWS so GKE is not relevant but point is valid for wider audience I guess;
3. Is it not possible to use Run Triggers? Not the same as tag trigger deployment though.

**Comment by pst** [comment]
I think it's a bit confusing how Terraform cloud workspaces and `terraform` cli workspaces have the same name but aren't quite the same thing.

But, a way I was able to make it work in a different context (application deployment) is to have workspaces in Terraform cloud with a prefix and then configuring the remote backend accordingly.

![Screenshot_2020-07-17 Workspaces couchallenge Terraform Cloud](https://user-images.githubusercontent.com/253456/87795835-e4337700-c848-11ea-8472-dbfa53970fd3.png)

Here's the [corresponding HCL](https://github.com/TooAngel/couchallenge/blob/87de8000bce7fa823b5f6a39b17316a20790453c/deploy/main.tf). This example was for a hackathon and I only used Terraform cloud to store the state. But if you have the provider in the repository it should also work when you have workspaces that run remotely.

Here's the [documentation regarding this prefix behavior](https://www.terraform.io/docs/backends/types/remote.html#prefix), were you use a prefix when creating the cloud workspace, but `terraform.workspace` will be the value without the prefix. So for Kubestack you would probably need to call the workspaces in Terraform cloud `myprefix-ops` and `myprefix-apps`, then configure the remote backend with `myprefix` as the prefix.
